export const ADD_TO_ORDER_REQUEST = 'ADD_TO_ORDER_REQUEST';
export const ADD_TO_ORDER_SUCCESS = 'ADD_TO_ORDER_SUCCESS';
export const ADD_TO_ORDER_FAILURE = 'ADD_TO_ORDER_FAILURE';
export const REMOVE_FROM_ORDER_REQUEST = 'REMOVE_FROM_ORDER_REQUEST';
export const REMOVE_FROM_ORDER_SUCCESS = 'REMOVE_FROM_ORDER_SUCCESS';
export const REMOVE_FROM_ORDER_FAILURE = 'REMOVE_FROM_ORDER_FAILURE';
export const MAKE_STRIPE_CHARGE = 'MAKE_STRIPE_CHARGE';
export const UPDATE_ORDER_TOTAL = 'UPDATE_ORDER_TOTAL';